# Generated by Django 6.1 on 2026-09-02 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='borrow_duration_in_days',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='borrowed_by',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
