# Generated by Django 6.1 on 2026-09-02 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0003_student_remove_book_borrow_duration_in_days_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libraryrecord',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='libraryrecord',
            old_name='student_id',
            new_name='student',
        ),
    ]
